Fix typo on README_ptbr.md
olmps/memo pull request #14
Opened 2021-03-30 16:43 UTC by RaphaelOliveiraMoura

Correções ortográficas:
- Adição de acento para a palavra depend**ê**ncias.
- Alteração de `.` para `;` como delimitador final para lista/sumário, seguindo o padrão dos outros tópicos.

## Pre-launch Checklist

- [x] Eu li o [CONTRIBUTING.md](../CONTRIBUTING.md) e segui as sugestões descritas ali sobre boas práticas de código / I
read [CONTRIBUTING.md](../CONTRIBUTING.md) and followed the suggestions proposed there about writing good code;
- [ ] Eu listei pelo menos um issue relacionado à este PR / I listed at least one issue related to this PR;
- [ ] Eu adicionei novos testes para cobrir as mudanças que eu fiz neste PR, ou este PR é uma exceção / I added new 
tests that cover the changes made in this PR or this PR is a test-exception;
- [ ] Eu atualizei o [CHANGELOG.md](./../CHANGELOG.md) com as mudanças feitas neste PR / I updated 
[CHANGELOG.md](./../CHANGELOG.md) with the changes made in this PR;
- [ ] Eu atualizei/adicionei comentários relevantes nas modificações efetuadas / I updated or added relevant docs in the
modifications I've made;
- [ ] Todos os testes previamente existentes e os novos criados por mim estão finalizando com sucesso / All the existing
tests - the old and the new ones - are finishing with success.

2021-03-30 18:14 UTC, RafaelKuhn approved these changes
👍

2021-03-31 01:28 UTC, ggirotto requested changes

2021-03-31 01:28 UTC, ggirotto commented on README_ptbr.md
> +- [Licença](#licença): como essa aplicação está licenciada e como você pode utilizá-la;
O último item de uma lista enumerada é finalizado com ponto final, indicando o final da lista. Se fossemos seguir a risca, o penúltimo item deveria também ter uma conjunção aditiva: `recomendações sobre contribuições; e`, porém acho que essa discussão de português formal não vai nos trazer benefícios. Vamos reverter essa alteração e manter o ponto final como tínhamos antes

Referência: https://www.ipea.gov.br/sites/en-GB/manualeditorial/padroes-editoriais/padronizacoes-textuais/enumeracoes

2021-03-31 01:28 UTC, ggirotto commented on README_ptbr.md
> +Agora, se você já tem o Flutter configurado localmente, na pasta raíz do projeto, instale as dependências através do
👍

2021-03-31 11:18 UTC, RaphaelOliveiraMoura commented on README_ptbr.md
> +- [Licença](#licença): como essa aplicação está licenciada e como você pode utilizá-la;
okay

2021-03-31 12:27 UTC, ggirotto approved these changes

2021-03-31 14:45 UTC, merged