Adds `LinkButton` and `ExternalLinkButton` widgets
olmps/memo pull request #69
Opened 2021-05-04 16:24 UTC by matuella

2021-05-04 17:15 UTC, ggirotto requested changes

2021-05-04 17:15 UTC, ggirotto commented on lib/application/constants/dimensions.dart
> +const double smallIconButtonPadding = 0;
0 const? It's not used in current PR. What's its purpose?

2021-05-04 20:40 UTC, ggirotto approved these changes

2021-05-05 18:22 UTC, matuella commented
All updates made and merged in the last PR (#76) in this nested chain of collection execution PRs

2021-05-05 18:22 UTC, closed without merging